---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: fnt-backend
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/fntapp/fnt-backend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: fnt-frontend
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/fntapp/fnt-frontend
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: fnt-scraper
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/fntapp/fnt-scraper
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: fnt-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/Vikaspogu/fnt_app