apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: fnt-backend-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build
    taskRef:
      name: s2i-go
      kind: Task
    params:
      - name: TLSVERIFY
        value: "false"
      - name: PATH_CONTEXT
        value: "go_backend"
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
  - name: deploy
    taskRef:
      name: openshift-client
      kind: ClusterTask
    runAfter:
      - build
    params:
    - name: ARGS
      value: "rollout latest fnt-backend"