apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: fnt-scraper
  namespace: fntapp
spec:
  template:
    metadata:
      annotations:
        # disable istio-proxy injection
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/fntapp/fnt-scraper:latest
        livenessProbe:
          httpGet:
            path: /
        readinessProbe:
          httpGet:
            path: /